Added rust-toolchain.toml, specifying nightly cargo in order to enable 'profile-rustflags'.
fixed the following error:

22;04:18_25 || main[ ] 0b5c384
$cargo test
error: failed to parse manifest at `./smalloc/Cargo.toml`

Caused by:
  the cargo feature `profile-rustflags` requires a nightly version of Cargo, but this is the `stable` channel
  See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.
  See https://doc.rust-lang.org/cargo/reference/unstable.html#profile-rustflags-option for more information about using this feature.